sudo: false
language: c
cache: ccache
script:
#
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
#

# Cleanup zip folder
- source build.sh <<< "1q"

#
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Google Branch is "google_gcc" | (1) 4.7 / (2) 4.8
# Linaro Branch is "linaro_gcc" | (1) 4.8.4 / (2) 4.9.4

# Toolchain branch select here is Google 4.7
- export ntoolchainbranch="google_gcc"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"

# ${ntoolchainchoice} is your Toolchain Choice
- export ntoolchainchoice="2"

# ${ntoolchain}
# "4" is "Toolchain Choice"
- ntoolchain="4${ntoolchainchoice}"

# ${ndevice}
# "2" is "Clean Kernel"
# "3" is "Device Choice"
- ndevice="23"

# ${ndevicechoice} is "Number of Choice under Device Choice"
# - export ndevicechoice="#"

# ${nbuild}
# "6" is "Build Kernel"
# "7" is "Zip the kernel and Modules"
# "q" is to Exit of Script
- nbuild="67q"

# Main variables
# Call of 'build.sh'
# - source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"

# TravisCI Custom Patches
- patch -p1 < ./zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch

# Build for LG L1 II Single/Dual | E410 E411 E415 E420
- export ndevicechoice="1"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
# Build for LG L3 II Single/Dual | E425 E430 E431 E435"
- export ndevicechoice="2"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
# Build for LG L5 NFC | E610
- export ndevicechoice="3"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
# Build for LG L5 NoNFC | E612 E617
- export ndevicechoice="4"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
# Build for LG L7 NFC | P700
- export ndevicechoice="5"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
# Build for LG L7 NoNFC | P705
- export ndevicechoice="6"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
# Build for LG L7 NFC 8m | P708
- export ndevicechoice="7"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "nni61sJP8PC5G90TAYKg7Ztmb89VlcrSbh+/I6An+rFsKEJrpuzXtV2qB5TPB1pZHKjqHFMhfGWhTpRVXX+yQPJpHUp/Zde+Gb58N0vnTDCRMm7kiPSgTLKGnPFri3MzeTVFUezdikTYS+htunZu8AWPww1QP8Ww+3oJ2K5+rb8="
  file_glob: true
  file:
    - "zip-creator/*.zip"
  on:
    tags: true
