sudo: false
language: c
cache: ccache
script:
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>

# Clone all necessary things
- git clone --single-branch -b "google_gcc" "https://github.com/TeamVee/android_prebuilt_toolchains" "android_prebuilt_toolchains"
- git clone --single-branch -b "android-msm-3.4-kk" "https://github.com/TeamHackLG/lge-kernel-lproj" "lge-kernel-lproj-kk"
- git clone --single-branch -b "android-msm-3.4-mm" "https://github.com/TeamHackLG/lge-kernel-lproj" "lge-kernel-lproj-mm"

#####

- cd lge-kernel-lproj-kk/

##### THE CORE STRIPPED OF .travis.yml FROM KK BRANCH
- source build.sh <<< "1q"
- patch -p1 < ./zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch

# Normal
- export ndevicechoice="1"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="2"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="3"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="4"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="5"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="6"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="7"
- source build.sh <<< "23${ndevicechoice}4167q"

# Overclocked
- patch -p1 < ../patchs/0000-build.sh-Change-to-KK-WithOverClock.patch
- patch -p1 < ../patchs/0001-acpuclock-7627-Update-7x25-7x27-clock.patch
- patch -p1 < ../patchs/0002-configs-Update-MAX-MIN-of-7x25-7x27-processors.patch
- export ndevicechoice="1"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="2"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="3"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="4"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="5"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="6"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="7"
- source build.sh <<< "23${ndevicechoice}4167q"
#####

- cd ../
- cd lge-kernel-lproj-mm/

##### THE CORE STRIPPED OF .travis.yml FROM MM BRANCH
- source build.sh <<< "1q"
- patch -p1 < ./zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch

# Normal
- export ndevicechoice="1"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="2"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="3"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="4"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="5"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="6"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="7"
- source build.sh <<< "23${ndevicechoice}4167q"

# Overclocked
- patch -p1 < ../patchs/0000-build.sh-Change-to-MM-WithOverClock.patch
- patch -p1 < ../patchs/0001-acpuclock-7627-Update-7x25-7x27-clock.patch
- patch -p1 < ../patchs/0002-configs-Update-MAX-MIN-of-7x25-7x27-processors.patch
- export ndevicechoice="1"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="2"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="3"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="4"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="5"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="6"
- source build.sh <<< "23${ndevicechoice}4167q"
- export ndevicechoice="7"
- source build.sh <<< "23${ndevicechoice}4167q"
#####

- cd ../
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "nni61sJP8PC5G90TAYKg7Ztmb89VlcrSbh+/I6An+rFsKEJrpuzXtV2qB5TPB1pZHKjqHFMhfGWhTpRVXX+yQPJpHUp/Zde+Gb58N0vnTDCRMm7kiPSgTLKGnPFri3MzeTVFUezdikTYS+htunZu8AWPww1QP8Ww+3oJ2K5+rb8="
  file_glob: true
  file:
    - "lge-kernel-lproj-kk/zip-creator/*.zip"
    - "lge-kernel-lproj-mm/zip-creator/*.zip"
  on:
    tags: true
